name: CI

on:
  push:
    branches:
      - "*" 

jobs:
  checkout-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ“¥ Checkout project
      uses: actions/checkout@v2

    - name: ğŸ”¨ Build .env from GitHub secrets
      run: |
        echo "DATABASE_URL='${{ secrets.DATABASE_URL }}'" >> .env
        echo "IMGUR_SECRET='${{ secrets.IMGUR_SECRET }}'" >> .env

    - name: ğŸ—ï¸ Create SSL keys from secrets
      run: |
        echo "${{ secrets.PK_SERVICE }}" > ./ssl/service-auth-public.pem
        echo "${{ secrets.PK_USER }}" > ./ssl/user-auth-public.pem
        echo "${{ secrets.SK_SERVICE }}" > ./ssl/service-auth-private.pem
        echo "${{ secrets.SK_USER }}" > ./ssl/user-auth-private.pem

    - name: ğŸ“¦ Install dependencies
      run: npm install

    - name: ğŸ§ª Execute tests
      run: npm run test
